apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: forprom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: forprom
subjects:
  - kind: ServiceAccount
    name: forprom
    namespace: prometheus
