apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: v1.9.8
  name: kube-state-metrics
  namespace: prometheus
spec:
  selector:
    app.kubernetes.io/name: kube-state-metrics
  type: NodePort
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
      nodePort: 32222
